spring.application.name=lode-manutencoes
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/lode_manutencoes
spring.datasource.username=lode
spring.datasource.password=lode123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
